// Template: Entity Framework 6 code-first DbContext + entity + migrations config — .NET Framework 4.x
// Package baseline: EntityFramework 6.2.0 (net461)
// Placeholders: {{Namespace}} {{Context}} {{Entity}}
//   {{Namespace}} -> Acme.Data   {{Context}} -> AcmeContext   {{Entity}} -> Product
//
// Setup (Package Manager Console, default project = this data project):
//   Enable-Migrations          (creates Migrations/Configuration.cs — once)
//   Add-Migration Initial      (scaffold first migration)
//   Update-Database            (apply to the DB named by "DefaultConnection")
using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace {{Namespace}}
{
    public class {{Context}} : DbContext
    {
        // "name=..." REQUIRES the named connection string in web.config/app.config (throws if missing).
        public {{Context}}() : base("name=DefaultConnection") { }

        public DbSet<{{Entity}}> {{Entity}}s { get; set; }
        public DbSet<Category> Categories { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<{{Entity}}>(e =>
            {
                e.ToTable("{{Entity}}s");
                e.HasKey(x => x.Id);
                e.Property(x => x.Name).IsRequired().HasMaxLength(200);
                e.Property(x => x.Price).HasPrecision(18, 2);
                e.HasRequired(x => x.Category)
                 .WithMany(c => c.{{Entity}}s)
                 .HasForeignKey(x => x.CategoryId);
            });

            base.OnModelCreating(modelBuilder);
        }
    }

    public class {{Entity}}
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }   // virtual => lazy-load capable (prefer Include())
    }

    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual System.Collections.Generic.ICollection<{{Entity}}> {{Entity}}s { get; set; }
    }

    // Migrations/Configuration.cs (generated by Enable-Migrations; shown for reference)
    internal sealed class Configuration : DbMigrationsConfiguration<{{Context}}>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;          // explicit migrations only (recommended)
            ContextKey = "{{Namespace}}.{{Context}}";
        }

        protected override void Seed({{Context}} context)
        {
            context.Categories.AddOrUpdate(c => c.Name, new Category { Name = "Default" });
        }
    }
}
